project:
  type: website
  output-dir: docs

website:
  title: "Eliana Shandalov"
  image: Users/elianashandalov/images/selfie.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - me.qmd
      - resume.qmd
      - posts.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
about:
  template: jolla
  image-shape: round
  image-width: 17em



