project:
  type: website
  output-dir: docs

website:
  title: "Eliana Shandalov"
  image: Users/elianashandalov/images/selfie.png
  navbar:
    title: false # override printing your website `title` (e.g. "Sam Csik" on line 6) in the top left corner of your navbar
    logo: file/path/to/logo.jpg
    logo-alt: "Alt text for logo"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - resume.qmd
      - me.qmd
  page-footer:
    background: dark
    left: Copyright 2025, Eliana Shandalov
  favicon: file/path/to/name.jpg # NOTE: that the `favicon` is a `website` level option (not under `navbar`)

format:
  html:
    theme:
      - quartz
      - $black: #000000
        - $navbar-bg: $black;
    mainfont: Montserrat
    toc: true

editor: visual
about:
  template: jolla
  image-shape: round
  image-width: 17em



