project:
  type: website
  output-dir: docs

website:
  title: "Eliana Shandalov"
  favicon: "elogo.png" # icon at tope of site
  image: Users/elianashandalov/images/selfie.png # add selfie to landing page
  navbar: # controls navigation bar at the top
    title: false # remove title
    logo: "ename.png" # logo from this image
    logo-alt: "Alt text for logo" # change where my name would be to logo thing
    left: # navbar will be aligned on the left
      - href: index.qmd # pages will be ordered this way
        text: Home
      - about.qmd
      - posts.qmd
      - resume.qmd
      - me.qmd
    background: "black"  # background of navbar will be black
    foreground: "lemonchiffon" # text color on navbar will be light yellow
  page-footer: # add a footer to the website
    background: dark # background of footer will be dark, other option is light
    left: Copyright 2025, Eliana Shandalov # text of footer

format:
  html:
    theme: quartz # customize theme
    css: styles.css # use this style page
    mainfont: Montserrat # customize font
    toc: true # show table of contents

editor: visual
about: # specify aspects of about page
  template: jolla # specifications of template on about page
  image-shape: round # make image round
  image-width: 17em # image width



